const KEY="appletech_store";const SESSION="appletech_admin_session";let store=JSON.parse(localStorage.getItem(KEY)||"{}");function save(){localStorage.setItem(KEY,JSON.stringify(store));renderCurrent();}
if(localStorage.getItem(SESSION)){loginView.hidden=true;panelView.hidden=false;}
function login(){if(u.value==='admin'&&p.value==='admin123'){localStorage.setItem(SESSION,'1');loginView.hidden=true;panelView.hidden=false;showTab('dashboard');}else alert('Credenciales inválidas');}
let current='dashboard';function showTab(t){current=t;renderCurrent();}
function renderCurrent(){if(current==='dashboard'){let c=store.catalog||[];tab.innerHTML=`<div class="result-card"><h3>Dashboard</h3><p>Total productos: ${c.length}</p><p>Disponibles: ${c.filter(x=>x.estado==='published').length}</p><p>Sin stock: ${c.filter(x=>(x.stock||0)<=0).length}</p></div>`;}if(current==='catalog'){let c=store.catalog||[];tab.innerHTML=`<div class="result-card"><h3>Catálogo</h3><input id="newName" class="select-input" placeholder="Nuevo modelo"><button class="btn btn-primary" onclick="addModel()">Agregar</button><hr>${c.map((m,i)=>`<div style="padding:8px;border-bottom:1px solid #333">${m.nombre}<br>Precio <input value="${m.precioBase||0}" onchange="store.catalog[${i}].precioBase=+this.value;save()"> Stock <input value="${m.stock||0}" onchange="store.catalog[${i}].stock=+this.value;save()"><select onchange="store.catalog[${i}].estado=this.value;save()"><option value="published" ${m.estado==='published'?'selected':''}>disponible</option><option value="out" ${m.estado==='out'?'selected':''}>sin stock</option><option value="hidden" ${m.estado==='hidden'?'selected':''}>oculto</option><option value="draft" ${m.estado==='draft'?'selected':''}>despublicado</option></select><button onclick="del(${i})">Eliminar</button></div>`).join('')}</div>`;}if(current==='contact'){let ct=store.contact||{};tab.innerHTML=`<div class="result-card"><h3>Contacto</h3><input id="phone" class="select-input" placeholder="Teléfono" value="${ct.phone||''}"><br><br><input id="wa" class="select-input" placeholder="WhatsApp" value="${ct.whatsapp||''}"><br><br><input id="ig" class="select-input" placeholder="Instagram" value="${ct.instagram||''}"><br><br><button class="btn btn-primary" onclick="saveContact()">Guardar</button></div>`;}}
function addModel(){if(newName.value){store.catalog.push({id:Date.now()+'',nombre:newName.value,precioBase:0,stock:0,estado:'draft'});save();}}
function del(i){if(confirm('Eliminar?')){store.catalog.splice(i,1);save();}}
function saveContact(){store.contact.phone=phone.value;store.contact.whatsapp=wa.value;store.contact.instagram=ig.value;save();}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(store,null,2)],{type:'application/json'}));a.download='AppleTech_Backup.json';a.click();}
showTab('dashboard');